AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS does not support duplicate private DNS entries for secrets manager service
  VPC endpoint. Presumably for the other private VPC endpoints as well.
  To handle this, manage said endpoints to a separate stack. Created on demand.
  And used for all environments.
Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
Resources:
  S3PrivateLink:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VpcId
      VpcEndpointType: Interface
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
      SubnetIds: !Ref SubnetIds
      SecurityGroupIds: [ !Ref SecurityGroupId ]
  SecretsManagerPrivateLink:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      VpcId: !Ref VpcId
      VpcEndpointType: Interface
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.secretsmanager'
      SubnetIds: !Ref SubnetIds
      SecurityGroupIds: [ !Ref SecurityGroupId ]
Outputs:
  S3PrivateLinkDnsEntry:
    Value: !Select ["0", !GetAtt S3PrivateLink.DnsEntries ]
    Export:
      Name: !Sub "${AWS::StackName}-S3PrivateLinkDnsEntry"
